### PR TITLE
Fix string formatting edge case

### LINKED ISSUE #126: Escape strings of HTML within <code> blocks
I have an element that looks like this:

```js
{ 
  '$$typeof': Symbol(react.element),
  type: 'code',
  key: 'h-4',
  ref: null,
  props:
   { className: 'language-javascript',
     children: [ '<div style={{ color: pink }}>123459254321</div>\n' ] },
  _owner: null,
  _store: {} 
}
```

It's a `<code>` element with JSX inside of it. 

The output from this module gives no special treatment to the JSX within the `<code>` element, so it ends up coming out as regular JSX: `<code><div style=...></div></code>`. Re-render that JSX and you have something different than what you started with.

I think this situation could be represented in JSX like `<code>{'<div style=...'}</div>`. You could also escape the `<` `>` signs, maybe.

I also think the same problem would apply to HTML within `<code>` blocks.

Do you think I'm misunderstanding something, or is this a bug?

### LINKED ISSUE #128: Don't mess json & jsx syntaxes - don't escape json in formatTreeNode
In [formatTreeNode()](https://github.com/algolia/react-element-to-jsx-string/blob/34c395261d88771449d226af92b0ff5f45fd1b22/src/formatter/formatTreeNode.js#L16-L18) we escape strings & numbers without going further in the kind of what the string represents. We recently had the case of a ld+json string being inside a script tag:
```html
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Hotel",
    "name": "Le Figuier",
    "description": "L’Hôtel Le Figuier est un petit établissement confortable et familial, au coeur d’Ivry-sur-Seine, à seulement 2km de Paris.",
    "address": "72 Boulevard de Brandebourg, 94200 Ivry-sur-Seine, France",
    "telephone": "+33 1 46 72 72 72",
    "photo": "https://res.cloudinary.com/karibbu/image/upload/c_scale,w_1800/v1501161224/lefiguier94.fr/VLWPuJuF7uUKLwMKZTytxg.jpg",
    "image": "https://res.cloudinary.com/karibbu/image/upload/s--P27nN2Ub--/v1501162649/lefiguier94.fr/Logo-lefiguier-light-bkg.svg",
    "starRating": {
        "@type": "Rating",
        "ratingValue": 0
    }
}
</script>
```

Yes it's a string, but it's a pure json string, encapsulated into script tags. So ATM the behavior escape it so it's rendered like that:
```html
<script type="application/ld+json">
&lbrace;
    "@context": "http://schema.org",
    "@type": "Hotel",
    "name": "Le Figuier",
    "description": "L’Hôtel Le Figuier est un petit établissement confortable et familial, au coeur d’Ivry-sur-Seine, à seulement 2km de Paris.",
    "address": "72 Boulevard de Brandebourg, 94200 Ivry-sur-Seine, France",
    "telephone": "+33 1 46 72 72 72",
    "photo": "https://res.cloudinary.com/karibbu/image/upload/c_scale,w_1800/v1501161224/lefiguier94.fr/VLWPuJuF7uUKLwMKZTytxg.jpg",
    "image": "https://res.cloudinary.com/karibbu/image/upload/s--P27nN2Ub--/v1501162649/lefiguier94.fr/Logo-lefiguier-light-bkg.svg",
    "starRating": &lbrace;
        "@type": "Rating",
        "ratingValue": 0
    &rbrace;
&rbrace;
</script>
```

And we expect to not having braces escaped. So the idea would be to make some extra assertions in formatTreeNode, something like that:
```js
/* @flow */

import formatReactElementNode from './formatReactElementNode';
import type { Options } from './../options';
import type { TreeNode } from './../tree';

const escape = (s: string): string =>
  s.replace(/{/g, '&lbrace;').replace(/}/g, '&rbrace;');

export default (
  node: TreeNode,
  inline: boolean,
  lvl: number,
  options: Options
): string => {
  if (node.type === 'number') {
    return node.value.toString();
  }

  if (node.type === 'string') {
    try {
      const json = JSON.parse(node.value);
      return JSON.stringify(json);
    } catch (error) {
      return escape(node.value.toString();
    }
  }

  if (node.type === 'ReactElement') {
    return formatReactElementNode(node, inline, lvl, options);
  }

  throw new TypeError(`Unknow format type "${node.type}"`);
};
```

### PR DESCRIPTION
**Pull request by Spy-Seth**
Fix #126
Fix #128

This will lead to a major release

### CODE REVIEW

File: src/formatter/formatTreeNode.js [hunk 1]
```diff
@@ -4,17 +4,30 @@ import formatReactElementNode from './formatReactElementNode';
 import type { Options } from './../options';
 import type { TreeNode } from './../tree';
 
-const escape = (s: string): string =>
-  s.replace(/{/g, '&lbrace;').replace(/}/g, '&rbrace;');
+const jsxStopChars = ['<', '>', '{', '}'];
+const shouldBeEscaped = (s: string) =>
+  jsxStopChars.some(jsxStopChar => s.includes(jsxStopChar));
+
+const escape = (s: string) => {
```
Comment (shouze) [inline src/formatter/formatTreeNode.js]: 👍
