### PR TITLE
Fix warning about access to PropTypes using React 15.5+ (fixes #213)

### LINKED ISSUE #213: "Warning: Accessing PropTypes via the main React package is deprecated" for React 15.5+
With commit https://github.com/algolia/react-element-to-jsx-string/commit/73d60526345e06f433929a7485abe1638e2da3da some import were changed to:

```js
import * as React from 'react';
```

In this case babel uses `_interopRequireWildcard` which is using `for..in` to make a copy of module exports. This cause to warning when React 15.5+ is using:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

Because with React 15.5, importing PropTypes from React is deprecated in favour of importing from the new 'prop-types' package.

### PR DESCRIPTION
**Pull request by lahmatiy**
Explicit import of React's types to avoid star import that leads to warning about access to PropTypes.

### CODE REVIEW

File: src/parser/parseReactElement.js [hunk 1]
```diff
@@ -1,15 +1,16 @@
...
 
-import * as React from 'react';
-import type { Options } from './../options';
+import React from 'react';
 import {
   createStringTreeNode,
   createNumberTreeNode,
   createReactElementTreeNode,
 } from './../tree';
+import type { Element as ReactElement } from 'react';
```
Comment (Mavrin) [inline src/parser/parseReactElement.js]: You could use one import from react
import React, { type Element as ReactElement } from 'react';

Comment (lahmatiy) [reply src/parser/parseReactElement.js]: Yep, that's work. Awesome! Thanks a lot!

Comment (Spy-Seth) [reply src/parser/parseReactElement.js]: `import React, { type Element as ReactElement } from 'react';`

Ho that's a good one! I didn't now it :D

**Comment by Spy-Seth** [comment]
Good job 👍
